import Footer from "@/components/partials/Footer";
import Navbar from "@/components/partials/Navbar";
import "@/styles/main.scss";
import type { AppProps } from "next/app";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>PRANTO SHIKDER</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Component {...pageProps} />
        <Footer />
      </main>
    </>
  );
}
